front_formulaire_secours:
    resource: "@FrontBundle/Controller/FormulaireSecoursController.php"
    type:     annotation

actualite_actualite:
    resource: "@ActualiteBundle/Controller/ActualiteController.php"
    type:     annotation


admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin



front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


actualite:
    resource: "@ActualiteBundle/Controller/"
    type:     annotation
    prefix:   /admin